//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NudgesTransactionHistory
    {
        public int TransactionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string SenderUserId { get; set; }
        public string ReciverUseId { get; set; }
        public string NudgeId { get; set; }
        public string NudgesGuidId { get; set; }
        public string SingleTransactionId { get; set; }
    }
}
